server:
    port: 9090

spring:
    application:
        name: author-api

management:
    endpoints:
        health:
            show-details: always
        web:
            exposure:
                include: '*'